---
- name: deploy jiraldap
  # hosts: ams1/ams1_overlay/toolbox
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install python and build dependencies
      yum:
        name:
        - python3
        - python3-pip

    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /opt/jiraldapsrc
        owner: root
        mode: 644
      with_items:
        - jiraldap
        - setup.py
        - requirements.txt

    - name: Install virtualenv package
      pip:
        executable: /bin/pip3.6
        name: virtualenv
        extra_args: --proxy proxy.ams1.cloud.ecg.so:3128

    - name: Install jiraldap dependencies
      pip:
        requirements: "/opt/jiraldapsrc/requirements.txt"
        virtualenv: "/opt/jiraldapenv"
        virtualenv_python: "/bin/python3.6"
        extra_args: --proxy proxy.ams1.cloud.ecg.so:3128

    - name: Install jiraldap
      shell: source /opt/jiraldapenv/bin/activate && cd  /opt/jiraldapsrc; python3.6 setup.py install
      args:
        executable: /bin/bash

    - name: link to script
      file:
        src: /opt/jiraldapenv/bin/jiraldap
        dest: /usr/local/sbin/jiraldap
        state: link
