---

- name: Add the HashiCorp yum repository
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install consul
  yum:
    name: consul
    state: present

- name: Touch missing consul.env file
  file:
    path: /etc/consul.d/consul.env
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: Configure consul as a server
  copy:
    src: consul.hcl
    dest: /etc/consul.d/consul.hcl
  notify:
   - consul_reconfigured

- name: Ensure service is enabled
  service:
    name: consul
    enabled: true