---
- name: deploy puppet
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: install puppet client
      command: "yum -y install puppet"
      args:
          warn: false

    - name: copy puppet.conf file
      copy:
        src: puppet.conf
        dest: /etc/puppet/puppet.conf
        owner: root
        mode: 0644

    - name: enable puppet service
      command: "systemctl enable puppet"

    - name: restart puppet agent
      command: "systemctl restart puppet"

    - name: run puppet agent (sign the cert in foreman)
      command: "puppet agent --waitforcert=240 -t"
      ignore_errors: yes

    # - name: run puppet agent (after cert sign in foreman)
    #   command: "puppet agent -t"
    #   ignore_errors: yes